/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rdtmxyctldkirzpfubog"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdG14eWN0bGRraXJ6cGZ1Ym9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzExNjcsImV4cCI6MjA3MjQwNzE2N30.m-BgmeB94GMnHXFY-NPHJkf7aKuTulLseF-QALH_cpo"